### PR TITLE
Adapt to removal of ifcfg.log

### PR DESCRIPTION
**Pull request by rvykydal**
ifcfg log was removed in
anaconda commit ba2ab17e7ff3e5db1030ed1a709056c2142329fc

### CODE REVIEW

**Comment by poncovka** [comment]
> Looks good to me. I wonder that pylint wasn't able to find this... :(

@jkonecny12, there are no tests for the initial-setup. The bug also mentions this:

> In general, we have seen this failure pattern multiple times at this point; I'd suggest some kind of test or at least process is needed upstream to ensure initial-setup gets checked whenever code is removed from anaconda.

@M4rtinK, I think that we should at least run the pylint checks on the initial-setup.

**Comment by jkonecny12** [comment]
Enabling pocketlint in the InitialSetup shouldn't be that problematic. It would be great to have it there.

**Comment by M4rtinK** [comment]
> Enabling pocketlint in the InitialSetup shouldn't be that problematic. It would be great to have it there.

Yep, that should work. Ideally this should also get run - either by Fedora gating or even from our Jenkins also for Anaconda releases, so that we prevent Initial Setup from breaking in the first place. :)

**Comment by jkonecny12** [comment]
Adding that for our jenkins shouldn't be a problem.

**Pull request merged**
