### PR TITLE
Migrate COPR builds from Jenkins to Packit

### PR DESCRIPTION
**Pull request by jkonecny12**
With this configuration all merged commits will be automatically build to our COPR repository.

My [TEST](https://github.com/jkonecny12/initial-setup/commit/4406251545ec87fb02384d8044704df832e439cc)

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by jkonecny12** [comment]
This is the last missing piece.

**Review by M4rtinK — APPROVED** [review]
Looks good to me & thanks a lot for all this, huge improvement! :)

**Comment by jkonecny12** [comment]
Merging now to solve this last piece. Not changing the code or make so it shouldn' t break anything.

**Pull request merged**
