### PR TITLE
Add gnome-kiosk to window managers usable by initial-setup

### PR DESCRIPTION
**Pull request by rvykydal**
Patch from vponcova@redhat.com

### CODE REVIEW

**Comment by rvykydal** [comment]
Related PR: https://src.fedoraproject.org/rpms/gnome-kiosk/pull-request/1

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well, thanks! :)

**Comment by M4rtinK** [comment]
BTW, one issue I found on Fedora is that the yelp window showing help content is full-screen and not decorated. I have also found no way to close it afterwards:
initial_setup_gnome_kiosk_wm
Strangely further Yelp windows launched from the yelps "hamburger" menu are not fullscreen and are decorated. Still as gnome-kiosk is quite unlikely to be used masively with Initial Setup on Fedora just yet, I think we can still go with merging this PR while fixing the Yelp window issue later (most likely on Gnome Kiosk side).

**Pull request merged**
