### PR TITLE
Add some more serial console options

### PR DESCRIPTION
**Pull request by nullr0ute**
Add some various new serial console to support devices from Samsung, QCom
and others

Signed-off-by: Peter Robinson <pbrobinson@gmail.com>

### CODE REVIEW

**Comment by M4rtinK** [comment]
Systemd recently merged the getty-pre.target patch set, so this (& the practice of listing all consoles by name in the service file) might no longer be needed in the future:

https://github.com/systemd/systemd/pull/6667

I'm trying to find out when is the feature going to land in Fedora (F27/Rawhide) so that we know if it makes sense to merge this PR or not.

**Comment by nullr0ute** [comment]
Well there's going to need to be a commit to clean it up either way so I'd sooner get this in initially so we can use it in F-27 as it's already at beta and we'd be better focusing on the systemd bits as an improvement in the F-28 cycle

**Comment by vpodzime** [comment]
> Well there's going to need to be a commit to clean it up either way so I'd sooner get this in initially so we can use it in F-27 as it's already at beta and we'd be better focusing on the systemd bits as an improvement in the F-28 cycle

Sounds good to me.

**Comment by M4rtinK** [comment]
> Well there's going to need to be a commit to clean it up either way so I'd sooner get this in initially so we can use it in F-27 as it's already at beta and we'd be better focusing on the systemd bits as an improvement in the F-28 cycle

Sounds good to me as well. :)

**Pull request merged**
